development:
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  pool: 5
  timeout: 5000
  host: localhost
  database: list_traders_development
test:
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  pool: 5
  timeout: 5000
  host: localhost
  database: list_traders_test
production:
  adapter: postgresql
  encoding: unicode
  username: 
  password: 
  pool: 5
  timeout: 5000
  host: localhost
  database: list_traders_production